// Generated by scripts/generate-thumbnails.cjs
export const movieThumbnails: Record<number, number> = {
  1: require('../images/thumbnails/movie2.webp'),
  3: require('../images/thumbnails/movie3.webp'),
  4: require('../images/thumbnails/movie4.webp'),
  5: require('../images/thumbnails/movie5.webp'),
  6: require('../images/thumbnails/movie6.webp'),
  7: require('../images/thumbnails/movie7.webp'),
  8: require('../images/thumbnails/movie8.webp'),
  9: require('../images/thumbnails/movie9.webp'),
  10: require('../images/thumbnails/movie10.webp'),
  11: require('../images/thumbnails/movie11.webp'),
  12: require('../images/thumbnails/movie12.webp'),
  13: require('../images/thumbnails/movie13.webp'),
  14: require('../images/thumbnails/movie14.webp'),
};
